
dir.create("data/cache", recursive = TRUE, showWarnings = FALSE) 
source("helpers/data_prep_experimental.R") 
source("helpers/data_prep_correlational.R") 
source("helpers/data_prep_mediators.R")
exp <- init_experimental_data("data/Dataset_MainNEW.xlsx") 
corr <- init_correlational_data("data/Dataset_Correlations.xlsx") 
mediators <- init_mediators_data("data/Dataset_MediatorsNEW.xlsx")
saveRDS(exp, "data/cache/exp_cache.rds") 
saveRDS(corr, "data/cache/corr_cache.rds")
saveRDS(mediators, "data/cache/mediators_cache.rds")
